name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set env
      run: echo "DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/doc-preview:latest,${{ secrets.DOCKERHUB_USERNAME }}/doc-preview:4.4.0-${{ env.DATE }}
        push: true
